import type { ResearchResult, TestScenario } from "../agent/research";
import type { PRInfo, IssueInfo } from "../utils/github";

/** Generate a Playwright E2E test file from research results */
export function generateE2ETest(
  target: PRInfo | IssueInfo,
  targetType: "pr" | "issue",
  research: ResearchResult,
  comfyUrl = "http://localhost:8188"
): string {
  const num = target.number;
  const title = target.title.replace(/'/g, "\\'");

  const scenarioBlocks = research.testScenarios
    .map((s, i) => generateScenarioTest(s, i, comfyUrl))
    .join("\n\n");

  return `// Auto-generated E2E test for ${targetType.toUpperCase()} #${num}
// ${title}
// ${target.url}
//
// Generated by comfy-qa — run with: bunx playwright test ${targetType}-${num}.e2e.ts

import { test, expect, type Page } from "@playwright/test";

const COMFY_URL = process.env.COMFY_URL ?? "${comfyUrl}";

test.describe("${targetType.toUpperCase()} #${num}: ${title}", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(COMFY_URL, { waitUntil: "networkidle", timeout: 30000 });
    // Wait for ComfyUI to fully initialize
    await page.waitForTimeout(2000);
  });

${scenarioBlocks}
});
`;
}

function generateScenarioTest(
  scenario: TestScenario,
  index: number,
  comfyUrl: string
): string {
  const stepsComment = scenario.steps
    .map((s, i) => `    // Step ${i + 1}: ${s}`)
    .join("\n");

  const preconditionsComment = scenario.preconditions
    .map((p) => `    // Precondition: ${p}`)
    .join("\n");

  return `  test("Scenario ${index + 1}: ${scenario.name.replace(/"/g, '\\"')}", async ({ page }) => {
    // ${scenario.description}
    //
    // Preconditions:
${preconditionsComment}
    //
    // Steps:
${stepsComment}
    //
    // Expected: ${scenario.expectedOutcome}
    // Playwright hint: ${scenario.playwrightHint}

    // --- AUTO-GENERATED SKELETON ---
    // This test provides the structure; the AI agent fills in
    // real selectors and assertions at runtime.

${generateStepCode(scenario)}

    // Verify expected outcome
    // TODO: Add assertion for: ${scenario.expectedOutcome}
  });`;
}

function generateStepCode(scenario: TestScenario): string {
  return scenario.steps
    .map((step, i) => {
      const lowered = step.toLowerCase();

      // Try to generate meaningful Playwright code from step descriptions
      if (lowered.includes("click") && lowered.includes("queue")) {
        return `    // Step ${i + 1}: ${step}
    const queueBtn = page.locator('button:has-text("Queue"), [data-testid="queue-button"]').first();
    if (await queueBtn.isVisible()) await queueBtn.click();`;
      }

      if (lowered.includes("wait") && (lowered.includes("preview") || lowered.includes("image"))) {
        return `    // Step ${i + 1}: ${step}
    await page.waitForTimeout(3000); // Wait for preview to appear`;
      }

      if (lowered.includes("switch") && lowered.includes("tab")) {
        return `    // Step ${i + 1}: ${step}
    const newTab = await page.context().newPage();
    await newTab.goto("about:blank");
    await newTab.waitForTimeout(3000);
    await newTab.close();
    await page.bringToFront();`;
      }

      if (lowered.includes("visibility") || lowered.includes("hidden")) {
        return `    // Step ${i + 1}: ${step}
    await page.evaluate(() => {
      Object.defineProperty(document, "hidden", { value: true, writable: true });
      document.dispatchEvent(new Event("visibilitychange"));
    });
    await page.waitForTimeout(2000);
    await page.evaluate(() => {
      Object.defineProperty(document, "hidden", { value: false, writable: true });
      document.dispatchEvent(new Event("visibilitychange"));
    });`;
      }

      if (lowered.includes("assert") || lowered.includes("verify") || lowered.includes("check")) {
        return `    // Step ${i + 1}: ${step}
    // TODO: Add specific assertion here
    await page.waitForTimeout(1000);`;
      }

      if (lowered.includes("scroll")) {
        return `    // Step ${i + 1}: ${step}
    await page.mouse.wheel(0, 300);
    await page.waitForTimeout(500);`;
      }

      // Generic fallback
      return `    // Step ${i + 1}: ${step}
    await page.waitForTimeout(1000);`;
    })
    .join("\n\n");
}
