import * as fs from "fs";
import * as path from "path";
import type { ResearchResult, QAChecklistItem } from "../agent/research";
import type { PRInfo, IssueInfo } from "../utils/github";

export interface ReportContext {
  target: PRInfo | IssueInfo;
  targetType: "pr" | "issue";
  research: ResearchResult;
  outputDir: string;
  screenshots: string[];
  videoPath?: string;
  runAt: Date;
}

function isPR(t: PRInfo | IssueInfo): t is PRInfo {
  return "headRefName" in t;
}

function severityBadge(s: string): string {
  const map: Record<string, string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🟢 LOW",
  };
  return map[s] ?? s.toUpperCase();
}

function statusIcon(s: string): string {
  const map: Record<string, string> = {
    pending: "⬜",
    pass: "✅",
    fail: "❌",
    blocked: "⛔",
  };
  return map[s] ?? "⬜";
}

function priorityBadge(p: string): string {
  const map: Record<string, string> = {
    P0: "🔥 P0",
    P1: "⚡ P1",
    P2: "📋 P2",
  };
  return map[p] ?? p;
}

export function generateMarkdownReport(ctx: ReportContext): string {
  const { target, targetType, research, screenshots, videoPath, runAt } = ctx;
  const num = target.number;
  const url = target.url;
  const title = target.title;

  const checklistTable = research.qaChecklist
    .map(
      (item) =>
        `| ${statusIcon(item.status)} | ${priorityBadge(item.priority)} | ${item.id} | ${item.category} | ${item.description} |`
    )
    .join("\n");

  const scenarioBlocks = research.testScenarios
    .map(
      (s, i) => `
### Scenario ${i + 1}: ${s.name}

> ${s.description}

**Preconditions:**
${s.preconditions.map((p) => `- ${p}`).join("\n")}

**Steps:**
${s.steps.map((step, j) => `${j + 1}. ${step}`).join("\n")}

**Expected Outcome:** ${s.expectedOutcome}

**Playwright Hint:** \`${s.playwrightHint}\`
`
    )
    .join("\n---\n");

  const checklistDetails = research.qaChecklist
    .map(
      (item) => `
#### ${item.id} — ${item.description}

- **Category:** ${item.category}
- **Priority:** ${priorityBadge(item.priority)}
- **Status:** ${statusIcon(item.status)} ${item.status}

**Steps:**
${item.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

**Expected Result:** ${item.expectedResult}
`
    )
    .join("\n---\n");

  const screenshotSection =
    screenshots.length > 0
      ? `
## Screenshots

${screenshots
  .map((s) => {
    const rel = path.basename(s);
    return `### ${rel}\n![${rel}](screenshots/${rel})\n`;
  })
  .join("\n")}`
      : "";

  const videoSection = videoPath
    ? `
## Video Recording

[Watch QA Session Video](${path.basename(videoPath)})

> Recorded with Comfy-QA Agent HUD overlay showing step-by-step operations.
`
    : `
## Video Recording

> ⚠️ Video recording requires a running ComfyUI instance. Start ComfyUI and re-run with \`--record\`.
`;

  return `# QA Report: ${targetType.toUpperCase()} #${num}

> **${title}**
> ${url}

---

## Executive Summary

${research.summary}

| Field | Value |
|-------|-------|
| Type | ${research.bugType} |
| Severity | ${severityBadge(research.severity)} |
| Affected Area | ${research.affectedArea} |
| Generated At | ${runAt.toISOString()} |
| Target | [${targetType.toUpperCase()} #${num}](${url}) |

---

## Bug Analysis

### Actual Behavior (The Bug)
${research.actualBehavior}

### Expected Behavior
${research.expectedBehavior}

### Root Cause
${research.rootCauseSummary}

---

## Reproduction Steps

${research.reproductionSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

---

## QA Checklist

| Status | Priority | ID | Category | Description |
|--------|----------|----|----------|-------------|
${checklistTable}

### Checklist Details

${checklistDetails}

---

## Test Scenarios

${scenarioBlocks}

---

## Risk Assessment

${research.risks.map((r) => `- ⚠️ ${r}`).join("\n")}

${research.relatedFiles.length > 0 ? `
## Related Files

${research.relatedFiles.map((f) => `- \`${f}\``).join("\n")}
` : ""}

${videoSection}

${screenshotSection}

---

*Generated by [Comfy-QA](https://github.com/snomiao/Comfy-QA) · ${runAt.toISOString()}*
`;
}

export function generateQASheet(ctx: ReportContext): string {
  const { target, targetType, research } = ctx;

  const rows = research.qaChecklist
    .map(
      (item) =>
        `| ${item.id} | ${item.description} | ${item.priority} | ${item.category} | ${item.status} | ${item.expectedResult} |`
    )
    .join("\n");

  return `# QA Test Sheet — ${targetType.toUpperCase()} #${target.number}

## ${target.title}

**Severity:** ${severityBadge(research.severity)}
**Area:** ${research.affectedArea}
**Tester:** _____________
**Date:** ${ctx.runAt.toISOString().split("T")[0]}

---

## Test Cases

| ID | Description | Priority | Category | Result | Expected Result |
|----|-------------|----------|----------|--------|-----------------|
${rows}

---

## Notes

_________________________________
_________________________________
_________________________________

## Sign-off

- [ ] All P0 items passed
- [ ] All P1 items passed or accepted with known issues
- [ ] Video evidence recorded
- [ ] Report filed

**QA Engineer:** _________________  **Date:** _________________
`;
}

export function saveReport(ctx: ReportContext): {
  reportPath: string;
  qaSheetPath: string;
  jsonPath: string;
} {
  const { outputDir, target, targetType } = ctx;
  fs.mkdirSync(outputDir, { recursive: true });

  const reportPath = path.join(outputDir, "report.md");
  const qaSheetPath = path.join(outputDir, "qa-sheet.md");
  const jsonPath = path.join(outputDir, "research.json");

  fs.writeFileSync(reportPath, generateMarkdownReport(ctx));
  fs.writeFileSync(qaSheetPath, generateQASheet(ctx));
  fs.writeFileSync(jsonPath, JSON.stringify({ target, research: ctx.research, runAt: ctx.runAt }, null, 2));

  console.log(`  [report] ${reportPath}`);
  console.log(`  [qa-sheet] ${qaSheetPath}`);
  console.log(`  [json] ${jsonPath}`);

  return { reportPath, qaSheetPath, jsonPath };
}
