/**
 * Comfy Registry — QA Evidence Video
 * Auto-generated by Research Agent on 2026-04-10
 * Score: 9/13 (69%)
 */
import { test, safeMove } from "./fixtures/fixture";
import { createVideoScript } from "../lib/demowright/dist/index.mjs";

test("comfy-registry QA evidence", async ({ page }) => {
  test.setTimeout(10 * 60_000);

  await page.goto("https://registry.comfy.org/", { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(3000);

  const script = createVideoScript()
    .title("Comfy Registry QA", {
      subtitle: "Score: 9/13 (69%)",
      durationMs: 3000,
    })

    // ── Landing Page (2/2) ──
    // ✅ view_hero (read) — PASS
    .segment("Welcome to the Comfy Registry — the central hub for finding and installing ComfyUI custom nodes.", async (pace) => {
      await pace();
    })
    // ✅ view_trending (read) — PASS
    .segment("Scrolling down, I can see the trending nodes — these are what the community is installing right now.", {
      setup: async () => {
        await page.mouse.wheel(0, 300);
      },
      action: async (pace) => {
        await pace();
      },
    })

    // ── Node Search (1/2) ──
    // ❌ search_by_name (read) — FAIL
    .segment("I want image upscaling, so I'm searching for SUPIR. Results appear instantly as I type — but this operation is currently failing.", {
      setup: async () => {
        await page.locator("input[type='search'], input[placeholder*='search'], input[placeholder*='Search'], .search-input, [data-testid='search']").first().click({ timeout: 5000 }).catch(() => {});
        await page.locator("input[placeholder='Search Nodes']").first().click({ timeout: 5000 }).catch(() => {});
        await page.waitForTimeout(1000);
        await page.locator("input[placeholder='Search Nodes']").first().click({ timeout: 5000 }).catch(() => {});
        await page.waitForTimeout(1000);
      },
      action: async (pace) => {
        await pace();
      },
    })
    // ✅ view_result_card (read) — PASS
    .segment("Each result card shows the name, version, publisher, download count, and tags — everything I need to decide at a glance.", {
      setup: async () => {
        await page.mouse.wheel(0, 300);
      },
      action: async (pace) => {
        await pace();
      },
    })

    // ── Node Detail (4/5) ──
    // ✅ view_node_page (read) — PASS
    .segment("Here's the detail page for ReActor Node — I can see the name, publisher badge, version, and download count right at the top.", {
      setup: async () => {
        await page.goto("https://registry.comfy.org/nodes/comfyui-reactor-node", { waitUntil: "domcontentloaded", timeout: 15000 });
      await page.waitForTimeout(1500);
      },
      action: async (pace) => {
        await pace();
      },
    })
    // ✅ view_readme (read) — PASS
    .segment("The README documentation is rendered right here — no more hunting through GitHub wikis.", async (pace) => {
      await pace();
    })
    // ✅ view_install_command (read) — PASS
    .segment("One command to install — just copy and paste into your terminal.", async (pace) => {
      await pace();
    })
    // ✅ view_version_history (read) — PASS
    .segment("The version history shows frequent updates — that means active maintenance and a healthy project.", async (pace) => {
      await pace();
    })
    // ❌ view_metadata (read) — FAIL
    .segment("The metadata sidebar tells me everything about compatibility — OS support, GPU accelerators, dependencies, and license — but this operation is currently failing.", {
      setup: async () => {
        await page.mouse.wheel(0, 300);
        await page.mouse.wheel(0, 300);
        await page.mouse.wheel(0, 300);
      },
      action: async (pace) => {
        await pace();
      },
    })

    // ── Publisher Profile (0/2) ──
    // ❌ navigate_to_publisher (read) — FAIL
    .segment("Clicking on the publisher name takes me to their profile where I can see all their other nodes — but this operation is currently failing.", {
      setup: async () => {
        await page.mouse.wheel(0, 300);
        await page.mouse.wheel(0, 300);
        await page.mouse.wheel(0, 300);
      },
      action: async (pace) => {
        await pace();
      },
    })
    // ❌ view_publisher_nodes (read) — FAIL
    .segment("If I trust one package from a developer, I probably want to check out everything else they've built — but this operation is currently failing.", {
      setup: async () => {
        await page.mouse.wheel(0, 300);
        await page.mouse.wheel(0, 300);
        await page.goto("https://registry.comfy.org/publishers/gosionr", { waitUntil: "domcontentloaded", timeout: 15000 });
      await page.waitForTimeout(1500);
      },
      action: async (pace) => {
        await pace();
      },
    })

    // ── Documentation (2/2) ──
    // ✅ view_docs_overview (read) — PASS
    .segment("The documentation covers everything from API endpoints to publishing guides and packaging requirements.", {
      setup: async () => {
        await page.goto("https://docs.comfy.org/registry/overview", { waitUntil: "domcontentloaded", timeout: 15000 });
      await page.waitForTimeout(1500);
      },
      action: async (pace) => {
        await pace();
      },
    })
    // ✅ view_publish_guide (read) — PASS
    .segment("Publishing your own node gives you a dedicated page with version tracking and download statistics.", {
      setup: async () => {
        await page.locator("[href*='publishing']").first().click({ timeout: 5000 }).catch(() => {});
      },
      action: async (pace) => {
        await pace();
      },
    })

    .outro({
      text: "QA Results: 9/13 (69%)",
      subtitle: "Landing Page 2/2 ✅ | Node Search 1/2 ⚠ | Node Detail 4/5 ⚠ | Publisher Profile 0/2 ⚠ | Documentation 2/2 ✅",
      durationMs: 5000,
    });

  await script.prepare(page);
  await script.render(page, {
    baseName: "comfy-registry-qa",
    outputDir: ".comfy-qa/.demos",
  });
});
